{% set name = "prometheus-fastapi-instrumentator" %}
{% set version = "8.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/prometheus_fastapi_instrumentator-{{ version }}.tar.gz
  sha256: 3c252e748151768a7aefd66824a04a870144f71de48a67aed211749a9ca2a548

build:
  skip: true  # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - poetry-core
  run:
    - starlette >=1.0.0,<2.0.0
    - prometheus_client >=0.8.0,<1.0.0
    - python

test:
  imports:
    - prometheus_fastapi_instrumentator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/trallnag/prometheus-fastapi-instrumentator
  summary: Instrument your FastAPI with Prometheus metrics
  description: A configurable and modular Prometheus Instrumentator for your FastAPI
  license: ISC
  license_file: LICENSE
  dev_url: https://github.com/trallnag/prometheus-fastapi-instrumentator
  doc_url: https://github.com/trallnag/prometheus-fastapi-instrumentator

extra:
  recipe-maintainers:
    - lsetiawan
